### ISSUE TITLE
Update -  all requests fail with 403

### ISSUE THREAD

**Issue by mzalewski** [ctate/autocode#27]
I was getting " Module (crystal/handlebars) does not exist in the Crystal Hub." when running autocode update in Windows.
After going through the source, it looks like github is rejecting the update request with a 403 error.

I think the issue is related to the request library - if I import sync-request into an empty project, and attempt to call the same url (including the User-Agent), I  get the same error. Using the 'request' (async) library works fine.

I've also tried in Ubuntu against the exact same code, and I'm running into the same issues.

**Comment by mzalewski** [comment]
After digging a bit more, the issue is caused by this line in the "http-basic" (used by sync-request->then-request):

Line 123:  options.headers = {};

The issue is a GET request to a repository in the github API returns a redirect response, and when redirected the http-basic module clears the headers. 

I've forked the http-basic library, added a fix - I'll send a pull request to the author as well but not sure if I'll get a response. 

For anyone interested, see my commit here: 
https://github.com/mzalewski/http-basic/commit/418a2ff7d5056c15815e4dfeabb8886805c12604

Closing this issue since it's not a problem with Autocode

**Comment by ctate** [comment]
Hey @mzalewski - nice work. I ran into the same issue after migrating our repos (see issue #26). I've also submitted a PR here: https://github.com/ForbesLindesay/http-basic/pull/7

Not sure which @ForbesLindesay prefers but might need to come up with a workaround. I've implemented a temporary fix on our servers. Hope to get this resolved for local soon. Sorry for the inconvenience.

**Comment by ctate** [comment]
@mzalewski Quick update - waiting for a fix to be approved for both `ForbesLindesay/http-basic` and `then/then-request`. In the meantime, I've updated the imports for Autocode and several other Autocode projects to avoid redirects. You can do the same by using `ctate` instead of `crystal` for anything I've created (i.e `ctate/handlebars` instead of `crystal/handlebars`).
